---
title: Title of Your Paper Here
author:
  - name: Zoya Azhar
    email: zazhar@smith.edu
    affiliation: Smith College
    footnote: Corresponding Author
  - name: Emeline Cox
    email: ecox@smith.edu
    affiliation: Smith College
  - name: Yejin Hwang
    email: yhwang67@smith.edu
    affiliation: Smith College
  - name: Kelly Pien
    email: kpien@smith.edu
    affiliation: Smith College
address:
  - code: Smith College
    address: Department of Economics, Pierce Hall, Northapmton, MA, 01063

abstract:
  WRITE AN ABSTRACT FOR YOUR PAPER HERE \par
  
  \textbf{JEL Classification:} D90 \par
  
  \textbf{Keywords:} Behavioral, Microeconomics, Present Bias, Time Inconsistency

bibliography: bibliography.bib
header-includes: \usepackage{float}
output: rticles::elsevier_article
---

```{r setup, include=FALSE}
## This chunk just sets it so that code will not show up on slides
knitr::opts_chunk$set(echo = FALSE)
```

```{r load libraries, message=FALSE, results='hide', echo=FALSE, warning=FALSE, include=FALSE}
#be warned...it takes a while
rm(list = ls()) #This clears the list databse
library(rticles)
library(tidyverse)
library(haven) #haven is part of tidyverse, but for some reason, this is needed.
library(ggplot2)
library(stargazer)
library(plm)
library(car)
library(cowplot) #plot side-by-side graphs
library(knitr) #to enable kable for testing. 
library(lfe) #To use the 'felm' command to run fixed effect linear models with clustering
```


```{r import data, echo=FALSE}
#Import your data in this code chunk
data1 <- read_dta("./data/final_data1.dta")
data2 <- read_dta("./data/final_data2.dta")
data3 <- read_dta("./data/final_data3.dta")
```


# 1. Introduction


# 2. Literature and Background 
@ajzen_theory_1991 proposed the theory of planned behavior which states that

# 3. Methods and Data


# 4. Reproduction of Abel et al. (2019)
```{r table1, results = "asis"}
controlGroup <- data1 %>% select(age_yr, female_d, educ_yr, bs_b15a, moved_yesno_d, bs_b1_ever_job_d, bs_b13_reserv_wage, bs_b14, bs_transport_cost, bs_b16, bs_c2, bs_c3)
names(controlGroup) <- c("Age", "Female", "Years of schooling", "Household size", "Moved to Johannesburg", "Ever employed", "Reservation wage", "Fair wage", "Job search transport cost", "Number employed friends", "Job search hours (week)", "Job applications (month)")
stargazer::stargazer(data.frame(controlGroup),
                     summary.stat = c("n", "mean", "median", "sd"),
                     type = "latex",
                     header = FALSE,
                     title = "Sample Characteristics")
```

```{r select relevant variables}
# Select variables in Table 2 from data1, put in dataframe d
vars <- c(34, 35, 36, 51, 52)
d <- data1[,vars]
```

```{r rename vars & create table, results = "asis"}
names(d) <- c("Goal: Opportunities to identify", "Goal: Applications to submit", "Goal: Job search hours", "Activity days", "Completed AP")
stargazer(data.frame(d),
          title = "Action-Plan Descriptives",
          omit.summary.stat = c("min", "max", "p25", "p75"),
          header = FALSE,
          type="latex")
```

```{r figure1, warning = FALSE}
hours_diff_density <- ggplot(data1, aes(hours_diff, stat(density))) +
  geom_histogram(fill = "#416b85", bins = 18) +
  labs(x = "Hours difference: Goal-Baseline", y = "Density") +
  ylim(0, 0.15)
apps_diff_density <- ggplot(data1, aes(apps_diff, stat(density))) +
  geom_histogram(fill = "#416b85", bins = 18) +
  labs(x = "Apps difference: Goal-Baseline", y = "Density")
f1_title <- ggdraw() + draw_label("Figure 1 - Intention-Behavior Gap: Difference at Baseline")
graph_grid <- plot_grid(hours_diff_density, apps_diff_density)
plot_grid(f1_title, graph_grid, ncol=1, rel_heights=c(0.1, 1))
```

```{r table3_reproduction, warning=FALSE, message=FALSE, results="asis"}
#Select only relevant data
t3_data <- data2 %>% select(b2_t, b3_t, ws_d, ws_plus_d,
                            nomiss_bs_c2, nomiss_bs_c3, missd_bs_c2, missd_bs_c3,
                            educ_yr, age_yr, female_d, bs_b15a, lang_xhosa_d, lang_venda_d, lang_zulu_d, location_f, round, id)

#Rename variables that will appear in table
colnames(t3_data)[colnames(t3_data) == "b2_t"] <- "Search_Hours"
colnames(t3_data)[colnames(t3_data) == "b3_t"] <- "Applications"
colnames(t3_data)[colnames(t3_data) == "ws_d"] <- "WS_basic"
colnames(t3_data)[colnames(t3_data) == "ws_plus_d"] <- "WS_plus"

#Build models
m1_t3 <- felm(Search_Hours ~ WS_basic + WS_plus +
                nomiss_bs_c2 + missd_bs_c2 + as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t3_data)
m2_t3 <- felm(Search_Hours ~ WS_basic + WS_plus +
                nomiss_bs_c2 + missd_bs_c2 +
                educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d +
                as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t3_data)
m3_t3 <- felm(Applications ~ WS_basic + WS_plus +
                nomiss_bs_c3 + missd_bs_c3 +
                as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t3_data)
m4_t3 <- felm(Applications ~ WS_basic + WS_plus +
                nomiss_bs_c3 + missd_bs_c3 +
                educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d +
                as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t3_data)

#Linear hypothesis tests to generate p-values
lh_m1_t3_p <- round(linearHypothesis(m1_t3, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m2_t3_p <- round(linearHypothesis(m2_t3, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m3_t3_p <- round(linearHypothesis(m3_t3, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m4_t3_p <- round(linearHypothesis(m4_t3, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)

#Generate table
stargazer(m1_t3, m2_t3, m3_t3, m4_t3,
          keep = c("WS_basic", "WS_plus"), keep.stat = c("n","rsq"),
          type = "latex",
          title= "Effects on Job Search Intensity",
          header = FALSE,
          add.lines = list(c("Covariates", "No", "Yes", "No", "Yes"),
                           c("p-value", lh_m1_t3_p, lh_m2_t3_p, lh_m3_t3_p, lh_m4_t3_p)))
```

```{r table4_reproduction, warning=FALSE, message=FALSE, results = "asis"}
#Select only relevant data
t4_data <- data2 %>% select(b4_t, b6_t, a1_t, ws_d, ws_plus_d,
                            nomiss_bs_c4, nomiss_bs_c6, missd_bs_c4, missd_bs_c6,
                            educ_yr, age_yr, female_d, bs_b15a, lang_xhosa_d, lang_venda_d, lang_zulu_d,
                            location_f, round, id)

#Rename variables that will appear in table
colnames(t4_data)[colnames(t4_data) == "b4_t"] <- "Responses"
colnames(t4_data)[colnames(t4_data) == "b6_t"] <- "Offers"
colnames(t4_data)[colnames(t4_data) == "a1_t"] <- "Employed"
colnames(t4_data)[colnames(t4_data) == "ws_d"] <- "WS_basic"
colnames(t4_data)[colnames(t4_data) == "ws_plus_d"] <- "WS_plus"

#Build models
m1_t4 <- felm(Responses ~ WS_basic + WS_plus +
                nomiss_bs_c4 + missd_bs_c4 + as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t4_data)
m2_t4 <- felm(Responses ~ WS_basic + WS_plus +
                nomiss_bs_c4 + missd_bs_c4 +
                educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d +
                as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t4_data)
m3_t4 <- felm(Offers ~ WS_basic + WS_plus +
                missd_bs_c6 +
                as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t4_data)
m4_t4 <- felm(Offers ~ WS_basic + WS_plus +
                missd_bs_c6 +
                educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d +
                as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t4_data)
m5_t4 <- felm(Employed ~ WS_basic + WS_plus +
                as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t4_data)
m6_t4 <- felm(Employed ~ WS_basic + WS_plus +
                educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d +
                as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t4_data)

#Linear hypothesis tests to generate p-values
lh_m1_t4_p <- round(linearHypothesis(m1_t4, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m2_t4_p <- round(linearHypothesis(m2_t4, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m3_t4_p <- round(linearHypothesis(m3_t4, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m4_t4_p <- round(linearHypothesis(m4_t4, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m5_t4_p <- round(linearHypothesis(m5_t4, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m6_t4_p <- round(linearHypothesis(m6_t4, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)

#Generate table
stargazer(m1_t4, m2_t4, m3_t4, m4_t4, m5_t4, m6_t4,
          keep = c("WS_basic", "WS_plus"), keep.stat = c("n","rsq"),
          type = "latex",
          title= "Effects on Employment Outcomes",
          header = FALSE,
          add.lines = list(c("Covariates", "No", "Yes", "No", "Yes", "No", "Yes"),
                           c("p-value", lh_m1_t4_p, lh_m2_t4_p, lh_m3_t4_p, lh_m4_t4_p, lh_m5_t4_p,lh_m6_t4_p)))
```

```{r table5, warning = FALSE, results = "asis"}
#Select only relevant data
t5_data <- data2 %>% select(b1_1_t, b1_2_t, b1_3_t, b1_4_t, b1_5_t, b1_6_t, ws_d, ws_plus_d, educ_yr, age_yr, female_d, bs_b15a, lang_xhosa_d, lang_venda_d, lang_zulu_d, nomiss_bs_c1_1, nomiss_bs_c1_2, nomiss_bs_c1_3, nomiss_bs_c1_4, nomiss_bs_c1_5, nomiss_bs_c1_6, missd_bs_c1_1, missd_bs_c1_2, missd_bs_c1_3, missd_bs_c1_4, location_f, round, id)

#Rename variables that will appear in table
colnames(t5_data)[colnames(t5_data) == "b1_1_t"] <- "Empl.agency"
colnames(t5_data)[colnames(t5_data) == "b1_2_t"] <- "Dropped_CV"
colnames(t5_data)[colnames(t5_data) == "b1_3_t"] <- "Placed_ad"
colnames(t5_data)[colnames(t5_data) == "b1_4_t"] <- "Answered_ad"
colnames(t5_data)[colnames(t5_data) == "b1_5_t"] <- "Searched_online"
colnames(t5_data)[colnames(t5_data) == "b1_6_t"] <- "Fam.friends"
colnames(t5_data)[colnames(t5_data) == "ws_d"] <- "WS_basic"
colnames(t5_data)[colnames(t5_data) == "ws_plus_d"] <- "WS_plus"

#Build models
m1_t5 <- felm(Empl.agency ~ WS_basic + WS_plus + educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d + nomiss_bs_c1_1 + missd_bs_c1_1 + as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t5_data)
m2_t5 <- felm(Dropped_CV ~ WS_basic + WS_plus + educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d + nomiss_bs_c1_2 + missd_bs_c1_2 + as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t5_data)
m3_t5 <- felm(Placed_ad ~ WS_basic + WS_plus + educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d + nomiss_bs_c1_3 + missd_bs_c1_3 + as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t5_data)
m4_t5 <- felm(Answered_ad ~ WS_basic + WS_plus + educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d + nomiss_bs_c1_4 + missd_bs_c1_4 + as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t5_data)
m5_t5 <- felm(Searched_online ~ WS_basic + WS_plus + educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d + nomiss_bs_c1_5 + as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t5_data) #missd_bs_c1_5 removed because it generated a coefficent of NaN which made the linearHypothesis test not work. my numbers here still match the paper's though.
m6_t5 <- felm(Fam.friends ~ WS_basic + WS_plus + educ_yr + age_yr + female_d + bs_b15a + lang_xhosa_d + lang_venda_d + lang_zulu_d + nomiss_bs_c1_6 + as.factor(location_f) + as.factor(round) | 0 | 0 | id, data = t5_data) #missd_bs_c1_6 removed for same reason

#Linear hypothesis tests to generate p-values
lh_m1_t5_p <- round(linearHypothesis(m1_t5, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m2_t5_p <- round(linearHypothesis(m2_t5, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m3_t5_p <- round(linearHypothesis(m3_t5, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m4_t5_p <- round(linearHypothesis(m4_t5, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m5_t5_p <- round(linearHypothesis(m5_t5, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)
lh_m6_t5_p <- round(linearHypothesis(m6_t5, c("WS_basic = WS_plus"))$`Pr(>Chisq)`[2], digits = 3)

#Generate table
stargazer(m1_t5, m2_t5, m3_t5, m4_t5, m5_t5, m6_t5,
          keep = c("WS_basic", "WS_plus"), keep.stat =c("n","rsq"),
          type = "latex",
          title="Effects on Frequency of Search-Channel Use",
          add.lines = list(c("p-value", lh_m1_t5_p, lh_m2_t5_p, lh_m3_t5_p, lh_m4_t5_p, lh_m5_t5_p, lh_m6_t5_p)),
          header = FALSE,
          table.placement = "H",
          column.sep.width = "-8pt")
```

# 5. Proposal 


# 6. Conclusion 





# References

